apiVersion: v1
kind: Secret
metadata:
  name: bankbot-secrets
type: Opaque
stringData:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: bankdb
  OPENAI_API_KEY: ORIGINAL KEYS REMOVED . REPLACE IT WITH YOUR OPENAI KEY